apiVersion: apps/v1
kind: Deployment
metadata:
  name: reading-service-deployment
  namespace: reading-list
  labels:
    app: reading-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reading-service
  template:
    metadata:
      labels:
        app: reading-service
    spec:
      containers:
      - name: reading-service
        image: sandkri3424/reading-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          value: "postgresql://bookkeeper:mybooks123@postgres-service:5432/reading_list"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until nc -z postgres-service 5432; do
            echo "PostgreSQL is not ready yet. Waiting..."
            sleep 2
          done
          echo "PostgreSQL is ready!"